import pysam
import sys

def filter_bam(input_bam, output_bam, min_identity=0.9, min_coverage=0.6):
    # Open the input BAM file
    infile = pysam.AlignmentFile(input_bam, "rb")
    # Create the output BAM file (with header information)
    outfile = pysam.AlignmentFile(output_bam, "wb", template=infile)

    count_total = 0
    count_pass = 0

    for read in infile:
        count_total += 1
        
        # 1. Skip unmapped reads
        if read.is_unmapped:
            continue

        # 2. Get total read length
        # query_length is the actual length of the sequence
        read_len = read.query_length
        if read_len == 0: # Sometimes secondary alignments may not have sequence information
            read_len = read.infer_query_length()

        # 3. Get aligned length
        # Count length of M (Match/Mismatch), I (Insertion), = (Match), and X (Mismatch) in CIGAR
        # get_cigar_stats()[0] returns an array where index 0=M, 1=I, 2=D, ...
        # Typically Aligned Length = M + I
        cigar_stats = read.get_cigar_stats()[0]
        aligned_len = cigar_stats[0] + cigar_stats[1] + cigar_stats[7] + cigar_stats[8] # M + I + = + X

        if aligned_len == 0:
            continue

        # 4. Calculate coverage
        coverage = aligned_len / read_len

        # 5. Calculate identity
        # Get NM tag (Edit Distance: Mismatches + Gaps)
        if read.has_tag("NM"):
            nm = read.get_tag("NM")
        else:
            # If NM tag is missing, skip or calculate manually (usually generated by BWA)
            continue
        
        # Identity = 1 - (Edit Distance / Aligned Length)
        identity = 1.0 - (nm / aligned_len)

        # 6. Apply filtering logic
        if coverage > min_coverage and identity > min_identity:
            outfile.write(read)
            count_pass += 1

    infile.close()
    outfile.close()
    print(f"Processed {count_total} reads. Kept {count_pass} reads.")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python filter_bam.py <input.bam> <output.bam>")
    else:
        filter_bam(sys.argv[1], sys.argv[2])